    create table ai_compare (
        app_id bigint,
        id bigint generated by default as identity,
        timestamp_created timestamp(6),
        timestamp_updated timestamp(6),
        domains TEXT,
        general TEXT,
        libraries TEXT,
        permissions TEXT,
        summary TEXT,
        version1 TEXT,
        version2 TEXT,
        primary key (id)
    );

    create table ai_generate (
        app_id bigint,
        id bigint generated by default as identity,
        timestamp_created timestamp(6),
        timestamp_updated timestamp(6),
        domains TEXT,
        general TEXT,
        libraries TEXT,
        permissions TEXT,
        summary TEXT,
        version TEXT,
        primary key (id)
    );

    create table app (
        is_critical boolean,
        is_pilot boolean,
        trend integer,
        category_id bigint,
        client_id bigint,
        date_added timestamp(6),
        date_tracking timestamp(6),
        id bigint generated by default as identity,
        lane_id bigint,
        last_app_control timestamp(6),
        last_app_update timestamp(6),
        last_status_change timestamp(6),
        last_updated timestamp(6),
        mbuc_id bigint,
        os_id bigint,
        priority_id bigint,
        referat_id bigint,
        software_nature_id bigint,
        software_type_id bigint,
        source_id bigint,
        status_id bigint,
        timestamp_created timestamp(6),
        timestamp_updated timestamp(6),
        visibility_id bigint,
        appstore_id TEXT,
        bundle_id TEXT,
        creator TEXT,
        description TEXT,
        e_key TEXT,
        epic_key TEXT,
        img TEXT,
        info_customer TEXT,
        info_url TEXT,
        mdm TEXT,
        name TEXT,
        number_of_users TEXT,
        rsm_key TEXT,
        primary key (id)
    );

    create table app_group (
        setting_control_interval INT DEFAULT 3 not null,
        setting_mail_app_removed BOOLEAN DEFAULT false not null,
        setting_mail_report BOOLEAN DEFAULT false not null,
        setting_mail_scan_degraded BOOLEAN DEFAULT false not null,
        setting_mail_scan_error BOOLEAN DEFAULT false not null,
        setting_mail_scan_success BOOLEAN DEFAULT false not null,
        color VARCHAR(7) DEFAULT '#0088ff' not null,
        id bigint generated by default as identity,
        mail varchar(254) not null,
        primary key (id)
    );

    create table app_group_assignment (
        app_group_id bigint,
        app_id bigint,
        id bigint generated by default as identity,
        primary key (id)
    );

    create table category (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table client (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table cosu_assignment (
        app_id bigint,
        cosu_config_id bigint,
        id bigint generated by default as identity,
        status_id bigint,
        primary key (id)
    );

    create table cosu_config (
        reference_id integer,
        category_id bigint,
        client_id bigint,
        date_added timestamp(6),
        id bigint generated by default as identity,
        lane_id bigint,
        last_updated timestamp(6),
        os_id bigint,
        priority_id bigint,
        referat_id bigint,
        status_id bigint,
        timestamp_created timestamp(6),
        timestamp_updated timestamp(6),
        description TEXT,
        e_key TEXT,
        epic_key TEXT,
        info_url TEXT,
        mdm_url TEXT,
        name TEXT,
        number_of_users TEXT,
        primary key (id)
    );

    create table file (
        cnt_files integer,
        app_id bigint,
        date_updated timestamp(6),
        file_type_id bigint,
        id bigint generated by default as identity,
        timestamp_created timestamp(6),
        timestamp_updated timestamp(6),
        file_name TEXT,
        size TEXT,
        version TEXT,
        primary key (id)
    );

    create table file_type (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table lane (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table mbuc (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table os (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table priority (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table provider (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table referat (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table scan (
        score integer,
        file_id bigint,
        id bigint generated by default as identity,
        provider_id bigint,
        timestamp_created timestamp(6),
        timestamp_updated timestamp(6),
        scan_key TEXT,
        primary key (id)
    );

    create table software_nature (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table software_type (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table source (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table status (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    create table timeline_event (
        type integer,
        id bigint generated by default as identity,
        reference_id bigint,
        status_id bigint,
        timestamp_end varchar(255),
        timestamp_start varchar(255),
        primary key (id)
    );

    create table visibility (
        id bigint generated by default as identity,
        name TEXT,
        primary key (id)
    );

    alter table if exists ai_compare
       add constraint FKi0np4ilgde4si6jxtkkyclppo
       foreign key (app_id)
       references app;

    alter table if exists ai_generate
       add constraint FKp86vutwqyhdrkuk435fygd6j6
       foreign key (app_id)
       references app;

    alter table if exists app
       add constraint FK3ec7rmfi01h9wphx2ymjhyy27
       foreign key (category_id)
       references category;

    alter table if exists app
       add constraint FK1b2py62aqjnoi4qenpvhc8tnq
       foreign key (client_id)
       references client;

    alter table if exists app
       add constraint FKd60xs154u4i3bdtlwaw5sjjkk
       foreign key (lane_id)
       references lane;

    alter table if exists app
       add constraint FKp24i1powkkoh77k475p4xa1h0
       foreign key (mbuc_id)
       references mbuc;

    alter table if exists app
       add constraint FK7ubq98kkqa3cqfpdv6ir62dc9
       foreign key (os_id)
       references os;

    alter table if exists app
       add constraint FK4pwwss0d9ggmqpmfxrjsxh4nn
       foreign key (priority_id)
       references priority;

    alter table if exists app
       add constraint FKoije41b8i4iulxa2b9t058k32
       foreign key (referat_id)
       references referat;

    alter table if exists app
       add constraint FK5i5uxt8h9ptmfq3nf8odw8onp
       foreign key (software_nature_id)
       references software_nature;

    alter table if exists app
       add constraint FK3nukvkmtcg51cjn5rbvdk561w
       foreign key (software_type_id)
       references software_type;

    alter table if exists app
       add constraint FK4s9d673qomdxb8bqi13h43div
       foreign key (source_id)
       references source;

    alter table if exists app
       add constraint FKhg701erqbup3x30ra8j1bo2sn
       foreign key (status_id)
       references status;

    alter table if exists app
       add constraint FKg90kjy53r694ft8aqlu80ofl
       foreign key (visibility_id)
       references visibility;

    alter table if exists app_group_assignment
       add constraint FKj4cxco8axe96w7r76wji8ihwg
       foreign key (app_id)
       references app
       on delete cascade;

    alter table if exists app_group_assignment
       add constraint FKagdpg7n4g83waysdymexa78e1
       foreign key (app_group_id)
       references app_group;

    alter table if exists cosu_assignment
       add constraint FKdqg27h9gwwq9033mgagkkr44j
       foreign key (app_id)
       references app;

    alter table if exists cosu_assignment
       add constraint FKrlpdgr4ay95kgq6wd6luu438
       foreign key (cosu_config_id)
       references cosu_config;

    alter table if exists cosu_assignment
       add constraint FKerp6kssxqy8g2bbskvh7028s4
       foreign key (status_id)
       references status;

    alter table if exists cosu_config
       add constraint FK80bxk2rk4kxnuoea1qijmab5k
       foreign key (category_id)
       references category;

    alter table if exists cosu_config
       add constraint FK3ip6n0ksn2b3nbsbow7rcjhs3
       foreign key (client_id)
       references client;

    alter table if exists cosu_config
       add constraint FK286ul8s9ledy4an7m2fw2wno7
       foreign key (lane_id)
       references lane;

    alter table if exists cosu_config
       add constraint FKmee0r4q2hpw3ntjmpj05652at
       foreign key (os_id)
       references os;

    alter table if exists cosu_config
       add constraint FK54sn8t9j1k5j7ps5hlx5ssl5k
       foreign key (priority_id)
       references priority;

    alter table if exists cosu_config
       add constraint FKd9ioaq9b9axdfcmp8xt6lv2la
       foreign key (referat_id)
       references referat;

    alter table if exists cosu_config
       add constraint FKpdlrmnfhvxkr74dharjiehjgw
       foreign key (status_id)
       references status;

    alter table if exists file
       add constraint FK92ygcut2holjs8ai0elj7ri1q
       foreign key (app_id)
       references app
       on delete cascade;

    alter table if exists file
       add constraint FKxd239i29el9tkqnnvdgpeoeb
       foreign key (file_type_id)
       references file_type;

    alter table if exists scan
       add constraint FKd18qtt12rpd0gj9ox4d74xku6
       foreign key (file_id)
       references file
       on delete cascade;

    alter table if exists scan
       add constraint FKh58xhl4y3t7b08cwwy7rtejg0
       foreign key (provider_id)
       references provider;

    alter table if exists timeline_event
       add constraint FKnlqawxtuycfpcyeqst9sr1nyx
       foreign key (reference_id)
       references app
       on delete cascade;

    alter table if exists timeline_event
       add constraint FK7o1rhja657ayxkyoa5aq5icee
       foreign key (status_id)
       references status;
